spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/finpulse_notes
      database: finpulse_notes

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.finpulse.notes: DEBUG
