spring:
  data:
    redis:
      timeout: 2000ms
  cache:
    type: redis
    redis:
      cache-null-values: false

stock:
  cache:
    quote-ttl-seconds: 60
    company-ttl-seconds: 86400
  default-provider: alpha-vantage

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: [health, info, metrics, prometheus, caches]
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      percentiles:
        "[http.server.requests]": 0.5, 0.95, 0.99
    tags:
      application: ${spring.application.name}

info:
  app:
    name: ${spring.application.name}
    description: Serviço de cotações de ações do FinPulse
    version: 0.0.1-SNAPSHOT
    java-version: 17
