spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

stock:
  providers:
    alpha-vantage:
      base-url: https://www.alphavantage.co
      api-key: ${ALPHA_VANTAGE_API_KEY}
    finnhub:
      base-url: https://finnhub.io/api/v1
      api-key: ${FINNHUB_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}

logging:
  level:
    root: WARN
    com.finpulse.stock: INFO
